language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=lentil tests/
after_success:
  - coveralls
