name: Bug report
description: Report a bug. 
title: "BUG: <Please write a title after the 'BUG: ' prefix>"
labels: [bug]

body:
- type: textarea
  attributes: 
    label: "Describe the issue:"
  validations:
    required: true
